spring:
  application:
    name: gateway

#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

zuul:
  routes:
    department:
      path: /department/**
    employee:
      path: /employee/**
    organization:
      path: /organization/**
  host:
    connect-timeout-millis: 120000
    connection-request-timeout-millis: 120000
    socket-timeout-millis: 120000

ribbon:
  connectTimeout: 60000
  ReadTimeout: 120000
  restclient:
    enabled: true
  eager-load:
    enabled: true

hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
